### ISSUE TITLE
tab "Tests" not here on some exercices  

### ISSUE THREAD

**Issue by Reunina** [exercism/elixir-test-runner#56] opened 2021-09-04 14:44 UTC
in the Hello world the tab is here but on other exercice the tab is missing: 
<img width="1427" alt="Capture d’écran 2021-09-04 à 16 40 30" src="https://user-images.githubusercontent.com/22769398/132098393-c2c1944a-4bcd-4cc1-9ac6-fd14cbfd5e49.png">

<img width="1287" alt="Capture d’écran 2021-09-04 à 16 41 41" src="https://user-images.githubusercontent.com/22769398/132098389-63ad5b62-0cc4-46a1-aff1-21b9c9033e70.png">

**Comment by jiegillet** [comment] 2021-09-04 14:55
This is by design, tests are not shown for concept exercises, because the instructions are a lot more detailed than the practice exercises and we want to push people to read them so they can effectively learn the techniques detailed in there.

**Comment by mpas97** [comment] 2021-09-04 19:52
I just wanted to report the same issue.

I don't think this "by design" is some kind of useful, as the results tab is also always shown, where in either way we can see all test commands with their expected results inside a drop-down list too. Second even if we stick to this choice, a user is very irritated as eg. the first exercise "hello world" is practice, the second "lasagna" is concept. Unaware of such categorization, we just click "next" and therefore we realize in exercise 2 already that something is missing. So a disabled button with a hint why it is deactivated would make more sense there. Although again, I don't see any information that would be hidden by removing this tab.

**Comment by angelikatyborska** [comment] 2021-09-04 19:54
@Reunina @mpas97 this issue would need to be discussed in https://github.com/exercism/exercism because it concerns the whole platform. The Elixir maintainers have no powers to change this on our own 😉.

**Comment by Reunina** [comment] 2021-09-05 14:42
thanks all for checking in :) 

I opened an issue here https://github.com/exercism/exercism/issues/5790 

@mpas97  feel free to modify it 😃

**Comment by angelikatyborska** [comment] 2021-09-05 15:01
Great! I'll close this one, let's see what other people say in exercism/exercism.

**Closed by angelikatyborska** 2021-09-05 15:01 UTC
